category: Example
description: This category contains example settings for unconfirm.
settings:
    skip_user_confirmation_dialog_on_close_form:
        description: >
            This setting will control if you are shown the confirmation dialog
            when you close the form.
        message: >
            Are you sure you want to close the form? All your settings will be
            lost if you do so.
        message_title: Are you sure?
        dont_show_text: Don't show this again.
        continue_text: Close the form
        cancel_text: Ah, let me rethink!
